import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { getSession } from "next-auth/react";

export async function getServerSideProps(context) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/api/auth/signin",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
export default function Home() {
  const { data: session } = useSession();
  console.log("session", session);
  console.log("session.user.role", session.user.role);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Content for regular user</h1>
        {session &&
          (session.user.role === "admin" ||
            session.user.role === "super-user") && (
            <Link href="/about">About for admin user</Link>
          )}
        {session && session.user.role === "super-user" && (
          <Link href="/super-user">Super User can access this component</Link>
        )}

        <Link href="/component-for-admin">
          Link to admin component to check role from within component
        </Link>
      </main>
    </>
  );
}
